### ISSUE TITLE
US2: Home Screen / Bestandsübersicht

### ISSUE THREAD

**Issue by MJ7898** [MJ7898/DLT-STAYF#10]
Als User möchte ich einen Überblick über meine Bestände an Coins und Coupons erhalten. Von dieser Übersicht aus möchte ich die anderen Menüs erreichen können.

Akzeptanzkriterien:
- [x] Andere Menüs sind von hier aus erreichbar
- [x] Aus anderen Menüs soll bei einer zurück-Interaktion dieses Menü erreicht werden können
- [x] Aktuelle Bestände an Coins und Coupons sind hier einzusehen

### TODO's
- [x] Menübar (bottom) 
- [x] navigation
- [x] Hauptseite 
- [x] Transaktionsseite
- [x] Transaktionsübersichtsseite

**Comment by MJ7898** [comment]
Aktueller Stand: 
- Das Frontend des HomeScreen ist fertig. Hier besteht lediglich noch die Notwendigkeit, die Informationen aus dem Backend zu erhalten und diese gegen die aktuellen PLATZHALTER zu ersetzen. D.h. Coupon-Rubrik ist erstellt. sowie die Account Übersicht / Balance, welche an Coins vorhanden ist.
