### ISSUE TITLE
US4: Transaktionsübersicht

### ISSUE THREAD

**Issue by MJ7898** [MJ7898/DLT-STAYF#12]
Als Bürger habe ich die Möglichkeit alle Transaktionen, in denen ich involviert bin. Hierbei sehe ich noch offene oder bereits abgeschlossene Transaktionen. (Transaktionshistorie)

Akzeptanzkriterien:
- [x] Anzeige muss scrollbar sein oder in Seiten aufgeteilt werden
- [x] Die einzelnen Transaktionen müssen von dieser Anzeige aus aufgerufen werden können
- [x] Offene und geschlossene TAs sollten unterschiedlich erkennbar sein (offene Trades sollen gehighlightet werden)
(- [ ] Es sollte möglich sein, die Liste nach Datum sortieren zu lassen)

### TODO's
- [x] Listenansicht mit Scrollbar
- [x] Listeneintrag eines Trades
- [x] Farbliche Unterscheidung von offenen und geschlossenen Trades
