### ISSUE TITLE
US5: Trade Detailansicht

### ISSUE THREAD

**Issue by MJ7898** [MJ7898/DLT-STAYF#13]
Als Bürger muss ich den Einfluss auf Trades haben. Wenn ein Trade angefragt wird, muss dieser durch die mitwirkende Person bestätigt werden können, damit der Trade als valide oder bestätigt gilt.

Akzeptanzkiterien: 
- [x] Trades in der Historie müssen als einzelne Items einsehbar sein. 
- [x] Übersicht des Trades als Pop up
- [x] Alle notwendigen Informationen (Art, Menge, Wert, Coins, Anbieter, "Käufer")

### TODO's
- [x] Detailansicht bei klick auf ein Listenelement
