### ISSUE TITLE
US1: SignUp / Login

### ISSUE THREAD

**Issue by MJ7898** [MJ7898/DLT-STAYF#9]
Als User möchte ich mich anmelden, bzw. registrieren können. 
Akzeptanzkriterien:
- [x] Anmeldeformular zur Erhebung personenspezifischer Daten
- [x] Wenn eine Person bereits ein Konto eröffnet hat, soll diese an die Login-Seite weitergeleitet werden

### TODO's
- [x] SignUp Formular
- [x] Login Maske
- [x] Ggf. Userverwaltung durch Google Firebase oder Mock-User

**Comment by MJ7898** [comment]
Ausstehende Punkte: 
- [ ] Review
